language: node_js

node_js:
  - '6'

cache:
  directories:
    - node_modules

script:
  - npm run build

deploy:
  provider: pages
  local_dir: _prod
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in this project's Travis CI Settings: https://travis-ci.org/WebVRRocks/webvr-lobby/settings
  on:
    branch: master
  name: GitHub-Pages-o-matic-o-tron
